# variables
- name: variables to print
  hosts: web
  vars:
    COURSES: "devops with aws"
    DURATION: "120hrs"
    TRAINER: "RAMANA"


  tasks:
    - name: print the information
      ansible.builtin.debug:
       msg: "hi, i am larning:{{COURSES}}, duration:{{DURATION}}, trainet:{{TRAINER}}"
