- name: install nginx
  hosts: web
  become: yes
  tasks:
    - name: gathering facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"
    - name: inatall nginx 
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_os_family == 'RedHat'
    - name: install nginx if debian
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible.os.family == 'Debian'